Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network = "forwarded_port", guest: 80, host: 8080"
  config.vm.network "private_network", ip: "192.168.0.1"
  config.vm.network "public_network"
end
