Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu"
    vb.memory = 1024
    vb.cpus = 2
  end
end
