---
- name: Setup the machine
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes


    - name: Upgrade packages
      apt:
        upgrade: yes


    - name: Create user account
      user:
        name: sardor
        password: "{{ '4697' | password_hash('sha512') }}"
        state: present
        groups: sudo
        append: yes


    - name: Generate SSH key pair
      command: "ssh-keygen -t rsa -b 4096 -C 'sardor@gmail.com' -f /home/sardor/.ssh/id_rsa -N ''"
      args:
        creates: "/home/sardor/.ssh/id_rsa"


    - name: Copy SSH public key to authorized_keys
      authorized_key:
        user: sardor
        key: "{{ lookup('file', '/home/sardor/.ssh/id_rsa.pub') }}"
        state: present
