Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu 2.3"
    vb.cpus = 2
    vb.memory = 1024
   end
  
  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "./hosts"
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
