Vagrant.configure("2") do |config|
  config.vm.define "ubuntu_1" do |ubuntu_1|
    ubuntu_1.vm.box = "ubuntu/bionic64"
    ubuntu_1.vm.hostname = "ubuntu1"
    ubuntu_1.vm.network "private_network", ip: "192.168.56.10"
    ubuntu_1.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu 1"
      vb.cpus = 2
      vb.memory = 2048
     end
    ubuntu_1.vm.provision "shell", path: "install_tools_ubuntu_1.sh"
   end 

  config.vm.define "ubuntu_2" do |ubuntu_2|
    ubuntu_2.vm.box = "ubuntu/xenial64"
    ubuntu_2.vm.hostname = "ubuntu2"
    ubuntu_2.vm.network "private_network", ip: "192.168.56.11"
    ubuntu_2.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu 2"
      vb.cpus = 1
      vb.memory = 1024 
     end
    ubuntu_2.vm.provision "shell", path: "install_tools_ubuntu_2.sh"
   end
end
